### PR TITLE
Improve code readability.

### PR DESCRIPTION
**Pull request by zangomboc**
Improve code readability.
Improve code readability.
Improve code readability.
Improve code readability.
Improve code readability.
Improve code readability.
Improve code readability.
Improve code readability.
Improve code readability.
Improve code readability.
Improve code readability.

### CODE REVIEW

**Comment by zangomboc** [comment]
Improve code readability.

**Review by zangomboc — COMMENTED** [review]
Ok. Code readable.

**Comment by zangomboc** [comment]
developer playing games, code still unreadable.

**Comment by rokmakovec** [comment]
no no u blind my man...the code is perfect

**Pull request closed without merging**
